"""`forseti enable-project --harness codex`: install/update the Codex verify-gate hook.

Writes/merges the `PostToolUse` `apply_patch` gate (`verify_hook.py`, dispatched via
`forseti codex-hook verify`) into a project's `.codex/config.toml` (#212). Every hook
entry `forseti` writes carries a `"forseti codex-hook "`-prefixed command, its
ownership marker -- same convention as the Claude Code adapter's `install.py`.

Unlike the Claude Code adapter (a JSON object merged at the dict level), this merges
at the *text* level: forseti's own managed block is delimited by a pair of sentinel
comment lines, stripped and regenerated wholesale on every run, then appended after
whatever else is already in the file. A dict-level round-trip through `tomllib` was
considered and rejected: `tomllib` has no writer, discards comments, and re-emitting
a parsed table as text has no ordering guarantee that keeps a document's own
top-level scalars (e.g. `notify`) ahead of its `[table]` headers -- TOML scopes any
key assigned after a header *into* that table, so a naive rewrite can silently move
an unrelated key into forseti's own table. A pure text splice can't do that: it never
touches a byte outside its own sentinel-delimited block, and appending our own table
headers at the very end can't rescope keys that were already valid earlier in the
file. The merged result is re-parsed with `tomllib` before it is ever written, so a
document a hand rewrite would corrupt (e.g. `hooks` already declared as an inline
table, making our appended `[[hooks.PostToolUse]]` an illegal redefinition) is caught
and rejected rather than silently producing invalid TOML.

Codex 0.148 rejects `notify` in project-local config as a user-level-only key --
forseti never emits it here; a user-level opt-in stays a separate, manual step.

Known residual: unlike the Claude Code adapter's `_LEGACY_HOOK_RE`, this installer
does not recognize the pre-#212 hand-copied `python3 "/abs/path/verify_hook.py"`
form from the old README as forseti's own -- a project that adopted the adapter
that way keeps that entry (now dead once the file moves) alongside forseti's own
freshly-installed block rather than having it migrated/removed. Not handled here;
revisit if it comes up.
"""

from __future__ import annotations

import re
import tomllib
from enum import Enum
from pathlib import Path

from forseti.adapters._atomic import write_text_atomic

_MARKER_PREFIX = "forseti codex-hook "
_HOOK_NAME = "verify"

HOOK_NAMES: frozenset[str] = frozenset({_HOOK_NAME})

_SENTINEL_START = (
    "# >>> forseti (managed) -- do not edit; regenerated by "
    "`forseti enable-project --harness codex` >>>"
)
_SENTINEL_END = "# <<< forseti (managed) <<<"

_BLOCK_RE = re.compile(
    re.escape(_SENTINEL_START) + r".*?" + re.escape(_SENTINEL_END) + r"\n?",
    re.DOTALL,
)


class InstallOutcome(Enum):
    """What `install` did to the target config file (`.value` is CLI-facing prose)."""

    CREATED = "installed"
    UPDATED = "updated"
    UNCHANGED = "already up to date"


class RemoveOutcome(Enum):
    """What `remove` did to the target config file (`.value` is CLI-facing prose)."""

    REMOVED = "removed"
    UNCHANGED = "already absent"


class ProjectConfigError(Exception):
    """The target config.toml can't be safely read/written as forseti's own."""


def _managed_block() -> str:
    command = f"{_MARKER_PREFIX}{_HOOK_NAME}"
    return (
        f"{_SENTINEL_START}\n"
        "[[hooks.PostToolUse]]\n"
        'matcher = "apply_patch"\n'
        "\n"
        "[[hooks.PostToolUse.hooks]]\n"
        'type = "command"\n'
        f'command = "{command}"\n'
        "timeout = 120\n"
        f"{_SENTINEL_END}\n"
    )


def _strip_managed_block(text: str) -> str:
    return _BLOCK_RE.sub("", text)


def _sentinel_in_parsed_data(value: object) -> bool:
    """True if a sentinel string occurs inside parsed TOML data, not a comment.

    `tomllib` discards comments entirely -- they never reach the parsed tree --
    so the only way parsed data can contain sentinel text is a TOML string
    literal (e.g. a copied example block hand-pasted into a prompt/notes
    value) that happens to embed it. That distinguishes a real collision from
    `_BLOCK_RE` matching our own already-installed comment block, without
    needing a full TOML-aware line scanner.
    """
    if isinstance(value, str):
        return _SENTINEL_START in value or _SENTINEL_END in value
    if isinstance(value, dict):
        return any(_sentinel_in_parsed_data(k) for k in value) or any(
            _sentinel_in_parsed_data(v) for v in value.values()
        )
    if isinstance(value, list):
        return any(_sentinel_in_parsed_data(v) for v in value)
    return False


def _refuse_sentinel_collision(existing_text: str, config_path: Path) -> None:
    try:
        parsed = tomllib.loads(existing_text)
    except tomllib.TOMLDecodeError:
        return
    if _sentinel_in_parsed_data(parsed):
        raise ProjectConfigError(
            f"{config_path}: forseti's sentinel text appears inside a TOML "
            "string value, not a comment -- refusing to touch it, since "
            "`_strip_managed_block` can't tell that apart from our own "
            "managed block and would silently delete part of that string"
        )


def _refuse_unpaired_sentinels(existing_text: str, config_path: Path) -> None:
    """Refuse text without exactly one well-formed sentinel pair, or none at all.

    `_BLOCK_RE`'s non-greedy match runs from the first START to the *next* END --
    given a stray, unpaired START (e.g. a half-reverted hand edit, or two managed
    files concatenated by a merge), it would silently consume everything up to
    some unrelated later END, deleting real content in between rather than
    raising. Since forseti only ever writes at most one pair, anything else --
    an unpaired START or END, or more than one pair -- means the file is already
    in a state forseti didn't produce, and it's not safe to guess which part (if
    any) is forseti's own block.
    """
    starts = existing_text.count(_SENTINEL_START)
    ends = existing_text.count(_SENTINEL_END)
    if starts == 0 and ends == 0:
        return
    if (
        starts == 1
        and ends == 1
        and existing_text.index(_SENTINEL_START) < existing_text.index(_SENTINEL_END)
    ):
        return
    raise ProjectConfigError(
        f"{config_path}: found {starts} forseti sentinel start marker(s) and "
        f"{ends} end marker(s), not one well-formed pair -- refusing to touch "
        "it, since a stray or duplicated sentinel could make the block-removal "
        "regex silently delete unrelated content between it and the next marker"
    )


def merge_config(existing_text: str, config_path: Path) -> str:
    """Return `existing_text` with forseti's managed block replaced by the current one.

    Raises `ProjectConfigError` if a `"forseti codex-hook "`-prefixed command exists
    *outside* the managed block (hand-edited) rather than risk installing a second,
    possibly-duplicate hook entry; if the sentinel text appears inside an existing
    TOML string value rather than a comment, or as an unpaired/duplicated marker
    (either would let `_strip_managed_block` silently delete unrelated content); and
    if the merged result fails to parse as TOML, rather than ever writing it.
    """
    _refuse_sentinel_collision(existing_text, config_path)
    _refuse_unpaired_sentinels(existing_text, config_path)
    stripped = _strip_managed_block(existing_text)
    if _MARKER_PREFIX in stripped:
        raise ProjectConfigError(
            f"{config_path}: found a `{_MARKER_PREFIX}...` command outside forseti's "
            "own managed block -- looks hand-edited; refusing to add a second, "
            "possibly-duplicate entry"
        )
    if stripped and not stripped.endswith("\n"):
        stripped += "\n"
    if stripped and not stripped.endswith("\n\n"):
        stripped += "\n"
    merged = stripped + _managed_block()
    try:
        tomllib.loads(merged)
    except tomllib.TOMLDecodeError as exc:
        raise ProjectConfigError(
            f"{config_path}: merging forseti's hook would produce invalid TOML ({exc}) "
            "-- not writing"
        ) from exc
    return merged


def _config_path(project_dir: Path) -> Path:
    return project_dir / ".codex" / "config.toml"


def install(project_dir: Path) -> tuple[Path, InstallOutcome]:
    """Install/update the Codex verify-gate hook for `project_dir`.

    Writes `.codex/config.toml`. Raises `ProjectConfigError` on unreadable/malformed
    existing TOML rather than overwriting it. The write is atomic (temp file +
    rename); a symlinked target raises `ProjectConfigError` rather than silently
    replacing the link with a plain file.
    """
    config_path = _config_path(project_dir)
    if config_path.is_symlink():
        raise ProjectConfigError(
            f"{config_path} is a symlink -- refusing to replace it (an atomic "
            "rewrite would swap in a plain file, silently breaking the link)"
        )
    existed = config_path.exists()
    if existed:
        try:
            existing_text = config_path.read_text(encoding="utf-8")
        except (OSError, ValueError) as exc:
            raise ProjectConfigError(
                f"{config_path}: cannot read existing config ({exc})"
            ) from exc
        try:
            tomllib.loads(existing_text)
        except tomllib.TOMLDecodeError as exc:
            raise ProjectConfigError(
                f"{config_path}: cannot parse existing config as TOML ({exc})"
            ) from exc
    else:
        existing_text = ""

    merged = merge_config(existing_text, config_path)
    if merged == existing_text:
        return config_path, InstallOutcome.UNCHANGED

    write_text_atomic(config_path, merged)
    outcome = InstallOutcome.CREATED if not existed else InstallOutcome.UPDATED
    return config_path, outcome


def remove(project_dir: Path) -> tuple[Path, RemoveOutcome]:
    """Remove forseti's own managed hook block from `project_dir`'s config.toml.

    No-ops -- and never creates the file, or otherwise touches a byte of it --
    if the config is absent or carries no forseti-owned block. Leaves every
    other key/table untouched; the blank-line separator `merge_config` inserts
    before its own block is trimmed back off, so a remove undoes an install
    byte-for-byte rather than leaving that artifact behind. The write is
    atomic (temp file + rename); a symlinked target raises `ProjectConfigError`
    rather than silently replacing the link with a plain file, as does sentinel
    text found inside a TOML string value rather than a comment, or an
    unpaired/duplicated sentinel marker.
    """
    config_path = _config_path(project_dir)
    if config_path.is_symlink():
        raise ProjectConfigError(
            f"{config_path} is a symlink -- refusing to replace it (an atomic "
            "rewrite would swap in a plain file, silently breaking the link)"
        )
    if not config_path.exists():
        return config_path, RemoveOutcome.UNCHANGED
    try:
        existing_text = config_path.read_text(encoding="utf-8")
    except (OSError, ValueError) as exc:
        raise ProjectConfigError(
            f"{config_path}: cannot read existing config ({exc})"
        ) from exc
    _refuse_sentinel_collision(existing_text, config_path)
    _refuse_unpaired_sentinels(existing_text, config_path)
    stripped = _strip_managed_block(existing_text)
    if stripped == existing_text:
        return config_path, RemoveOutcome.UNCHANGED
    trailing_newlines = len(stripped) - len(stripped.rstrip("\n"))
    if trailing_newlines <= 2:
        # `merge_config` pads at most up to a two-newline (blank-line) separator
        # before appending its block, so <=2 trailing newlines here can't be told
        # apart from a genuine 0/1/2-newline original -- collapse to one. Beyond
        # two, `merge_config` never strips existing newlines, so any extra ones
        # can only be the original file's own EOF whitespace; preserve them
        # exactly instead of normalizing them away.
        stripped = stripped.rstrip("\n")
        if stripped:
            stripped += "\n"
    write_text_atomic(config_path, stripped)
    return config_path, RemoveOutcome.REMOVED
