"""`forseti enable-project --harness oh-my-pi`: install/update the Oh My Pi gate (#249).

Unlike the Codex/Claude Code installers, this one manages *two* artifacts in a
target project:

1. `.omp/extensions/forseti-gate.ts` — the native extension (`verify_hook.py`'s
   module docstring). Whole-file, not merged: `_EXTENSION_SOURCE` below is
   embedded verbatim (Forseti's own `setuptools.packages.find` only packages
   `src/forseti/`, so there is no `adapters/oh-my-pi/forseti-gate.ts` on disk
   to read at install time the way there would be from a source checkout —
   the same reason the Codex/Claude Code installers generate their config
   from Python constants instead of copying a file). The repo-root
   `adapters/oh-my-pi/forseti-gate.ts` is kept as a human-readable reference
   copy; `test_omp_install.py` pins the two together so they can't drift.
2. `.omp/mcp.json` — merged at the dict level (the `mcpServers.forseti` key
   only), the same style the Claude Code installer already uses for
   `settings.json`.

Both are gated on an ownership check before any overwrite/removal: the
extension file must start with forseti's own sentinel comment, and an
existing `mcpServers.forseti` entry must have `"command": "forseti"` — a
project with either one hand-edited or hand-authored (not forseti's own) is
left untouched, and `install`/`remove` raise `ProjectConfigError` rather than
risk clobbering it.
"""

from __future__ import annotations

import json
from enum import Enum
from pathlib import Path
from typing import Any

from forseti.adapters._atomic import write_text_atomic

HOOK_NAMES: frozenset[str] = frozenset({"tool-result"})

_MARKER_START = (
    "// >>> forseti (managed) -- do not edit; regenerated by\n"
    "// `forseti enable-project --harness oh-my-pi` >>>"
)
_MARKER_END = "// <<< forseti (managed) <<<"

_SERVER_NAME = "forseti"
_FORSETI_SERVER: dict[str, Any] = {"command": "forseti", "args": ["mcp"]}

# Kept byte-identical to `adapters/oh-my-pi/forseti-gate.ts` (module docstring;
# pinned by `test_omp_install.py::test_extension_source_matches_reference_file`).
_EXTENSION_SOURCE = """\
// >>> forseti (managed) -- do not edit; regenerated by
// `forseti enable-project --harness oh-my-pi` >>>
//
// Forseti's Oh My Pi extension (#249): after a `write`/`edit` tool call
// lands, shell out to `forseti omp-hook tool-result` and let it decide
// whether the edit's stored semantic properties still hold. All Core logic
// (ESBMC invocation, harness rendering, the property store) lives in the
// `forseti` CLI -- this extension only serializes the event, calls it, and
// applies its JSON reply to the tool result.
//
// Uses `node:child_process.spawnSync` rather than the extension API's own
// `pi.exec` helper: `pi.exec` streams stdout via an `onData` callback and
// has no stdin parameter, while `forseti omp-hook tool-result` expects one
// JSON object on stdin and prints one JSON reply on stdout -- the same
// contract `spawnSync`'s `input`/`stdout` options give directly.
//
// A `tool_result` handler's returned `isError` *is* applied by Oh My Pi's
// current `ExtensionToolWrapper` (verified against
// packages/coding-agent/src/extensibility/extensions/wrapper.ts), unlike
// the legacy `HookToolWrapper` docs/hooks.md describes -- so a VIOLATED
// verdict here reads to the model as the edit itself having failed, not
// merely as an aside.
//
// `spawnSync` does not throw on a launch failure or a timeout -- it returns
// normally with `error` set (Node.js semantics), so a killed/never-started
// `forseti` process must be checked explicitly rather than relied on to
// fall into a catch block. Every spawn failure (including `forseti` missing
// from PATH), a nonzero exit, or an unparseable reply is reported as an
// inconclusive result instead of read as a silent pass -- the empty-stdout
// case is a legitimate pass only when the process actually exited cleanly.

import { spawnSync } from "node:child_process";
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

const GATED_TOOLS = new Set(["write", "edit"]);

function notAPass(event: { content: unknown[] }, detail: string) {
  const text = `Forseti gate did not complete (${detail}). Not a pass.`;
  return { content: [...event.content, { type: "text" as const, text }] };
}

export default function forsetiGate(pi: ExtensionAPI): void {
  pi.on("tool_result", async (event, ctx) => {
    if (!GATED_TOOLS.has(event.toolName) || event.isError) return;

    const proc = spawnSync("forseti", ["omp-hook", "tool-result"], {
      cwd: ctx.cwd,
      input: JSON.stringify({
        toolName: event.toolName,
        input: event.input,
        isError: event.isError,
        cwd: ctx.cwd,
      }),
      encoding: "utf-8",
      timeout: 180_000,
    });

    if (proc.error) {
      return notAPass(event, proc.error.message);
    }
    if (proc.status !== 0) {
      return notAPass(event, `forseti exited ${proc.status}`);
    }

    const stdout = proc.stdout?.trim();
    if (!stdout) return; // main() printed nothing -- a legitimate pass

    let reply: { decision?: string; reason?: string; systemMessage?: string };
    try {
      reply = JSON.parse(stdout);
    } catch {
      return notAPass(event, "unparseable reply");
    }

    const message = reply.decision === "block" ? reply.reason : reply.systemMessage;
    if (!message) return;

    return {
      content: [...event.content, { type: "text" as const, text: message }],
      isError: reply.decision === "block" ? true : event.isError,
    };
  });
}
// <<< forseti (managed) <<<
"""


class InstallOutcome(Enum):
    """What `install` did to the target project (`.value` is CLI-facing prose)."""

    CREATED = "installed"
    UPDATED = "updated"
    UNCHANGED = "already up to date"


class RemoveOutcome(Enum):
    """What `remove` did to the target project (`.value` is CLI-facing prose)."""

    REMOVED = "removed"
    UNCHANGED = "already absent"


class ProjectConfigError(Exception):
    """A target file exists but cannot be safely written/removed as forseti's own."""


def _extension_path(project_dir: Path) -> Path:
    return project_dir / ".omp" / "extensions" / "forseti-gate.ts"


def _is_forseti_extension(text: str) -> bool:
    return text.startswith(_MARKER_START)


def _install_extension(project_dir: Path) -> tuple[Path, InstallOutcome]:
    path = _extension_path(project_dir)
    if path.is_symlink():
        raise ProjectConfigError(
            f"{path} is a symlink -- refusing to replace it (an atomic "
            "rewrite would swap in a plain file, silently breaking the link)"
        )
    existed = path.exists()
    if existed:
        try:
            existing_text = path.read_text(encoding="utf-8")
        except (OSError, ValueError) as exc:
            raise ProjectConfigError(
                f"{path}: cannot read existing extension ({exc})"
            ) from exc
        if not _is_forseti_extension(existing_text):
            raise ProjectConfigError(
                f"{path}: does not look like forseti's own managed extension "
                "(missing its sentinel header) -- refusing to overwrite "
                "hand-written content"
            )
        if existing_text == _EXTENSION_SOURCE:
            return path, InstallOutcome.UNCHANGED

    write_text_atomic(path, _EXTENSION_SOURCE)
    return path, InstallOutcome.CREATED if not existed else InstallOutcome.UPDATED


def _remove_extension(project_dir: Path) -> tuple[Path, RemoveOutcome]:
    path = _extension_path(project_dir)
    if path.is_symlink():
        raise ProjectConfigError(
            f"{path} is a symlink -- refusing to replace it (an atomic "
            "rewrite would swap in a plain file, silently breaking the link)"
        )
    if not path.exists():
        return path, RemoveOutcome.UNCHANGED
    try:
        existing_text = path.read_text(encoding="utf-8")
    except (OSError, ValueError) as exc:
        raise ProjectConfigError(
            f"{path}: cannot read existing extension ({exc})"
        ) from exc
    if not _is_forseti_extension(existing_text):
        raise ProjectConfigError(
            f"{path}: does not look like forseti's own managed extension "
            "(missing its sentinel header) -- refusing to delete hand-written content"
        )
    path.unlink()
    return path, RemoveOutcome.REMOVED


def _mcp_config_path(project_dir: Path) -> Path:
    return project_dir / ".omp" / "mcp.json"


def _is_forseti_server(value: object) -> bool:
    return isinstance(value, dict) and value.get("command") == "forseti"


def _read_existing_mcp_config(config_path: Path) -> dict[str, Any]:
    if not config_path.exists():
        return {}
    try:
        existing = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ProjectConfigError(
            f"{config_path}: cannot read existing MCP config ({exc})"
        ) from exc
    if not isinstance(existing, dict):
        raise ProjectConfigError(f"{config_path}: top-level JSON must be an object")
    return existing


def merge_mcp_config(existing: dict[str, Any], config_path: Path) -> dict[str, Any]:
    """Return `existing` with `mcpServers.forseti` set to forseti's own entry.

    Every other key -- `$schema`, `disabledServers`, `enabledServers`, other
    `mcpServers` entries -- survives unchanged. Raises `ProjectConfigError` if
    `mcpServers` isn't an object, or if a `forseti`-named entry already exists
    with a `command` other than `"forseti"` -- that is a hand-configured
    server that happens to share the name, not forseti's own to overwrite.
    """
    merged = dict(existing)
    servers_raw = merged.get("mcpServers", {})
    if not isinstance(servers_raw, dict):
        raise ProjectConfigError(
            f'{config_path}: existing "mcpServers" must be an object'
        )
    servers = dict(servers_raw)
    current = servers.get(_SERVER_NAME)
    if current is not None and not _is_forseti_server(current):
        raise ProjectConfigError(
            f'{config_path}: an "mcpServers.{_SERVER_NAME}" entry already exists '
            'and does not look like forseti\'s own (no "command": "forseti") -- '
            "refusing to overwrite a hand-configured server"
        )
    servers[_SERVER_NAME] = dict(_FORSETI_SERVER)
    merged["mcpServers"] = servers
    return merged


def _strip_mcp_server(existing: dict[str, Any], config_path: Path) -> dict[str, Any]:
    servers_raw = existing.get("mcpServers")
    if servers_raw is None:
        return existing
    if not isinstance(servers_raw, dict):
        raise ProjectConfigError(
            f'{config_path}: existing "mcpServers" must be an object'
        )
    if _SERVER_NAME not in servers_raw:
        return existing
    current = servers_raw[_SERVER_NAME]
    if not _is_forseti_server(current):
        raise ProjectConfigError(
            f'{config_path}: "mcpServers.{_SERVER_NAME}" does not look like '
            'forseti\'s own (no "command": "forseti") -- refusing to remove it'
        )
    stripped = dict(existing)
    servers = dict(servers_raw)
    del servers[_SERVER_NAME]
    if servers:
        stripped["mcpServers"] = servers
    else:
        stripped.pop("mcpServers", None)
    return stripped


def _install_mcp_config(project_dir: Path) -> tuple[Path, InstallOutcome]:
    config_path = _mcp_config_path(project_dir)
    if config_path.is_symlink():
        raise ProjectConfigError(
            f"{config_path} is a symlink -- refusing to replace it (an atomic "
            "rewrite would swap in a plain file, silently breaking the link)"
        )
    existed = config_path.exists()
    existing = _read_existing_mcp_config(config_path)
    merged = merge_mcp_config(existing, config_path)
    if merged == existing:
        return config_path, InstallOutcome.UNCHANGED
    write_text_atomic(config_path, json.dumps(merged, indent=2) + "\n")
    return (
        config_path,
        InstallOutcome.CREATED if not existed else InstallOutcome.UPDATED,
    )


def _remove_mcp_config(project_dir: Path) -> tuple[Path, RemoveOutcome]:
    config_path = _mcp_config_path(project_dir)
    if config_path.is_symlink():
        raise ProjectConfigError(
            f"{config_path} is a symlink -- refusing to replace it (an atomic "
            "rewrite would swap in a plain file, silently breaking the link)"
        )
    if not config_path.exists():
        return config_path, RemoveOutcome.UNCHANGED
    existing = _read_existing_mcp_config(config_path)
    stripped = _strip_mcp_server(existing, config_path)
    if stripped == existing:
        return config_path, RemoveOutcome.UNCHANGED
    write_text_atomic(config_path, json.dumps(stripped, indent=2) + "\n")
    return config_path, RemoveOutcome.REMOVED


def install(project_dir: Path) -> tuple[Path, InstallOutcome]:
    """Install/update the Oh My Pi verify-gate extension + MCP registration.

    Writes `.omp/extensions/forseti-gate.ts` and merges `mcpServers.forseti`
    into `.omp/mcp.json` (module docstring). Raises `ProjectConfigError`
    before writing either artifact that isn't safely forseti's own to
    overwrite. If the extension write succeeds but the MCP merge then raises
    (e.g. a foreign `mcpServers.forseti` entry), the extension write is left
    in place -- both artifacts are independently idempotent, so a rerun after
    resolving the conflict completes the other half rather than needing a
    full redo.
    """
    omp_dir = project_dir / ".omp"
    existed = omp_dir.exists()
    _, ext_outcome = _install_extension(project_dir)
    _, mcp_outcome = _install_mcp_config(project_dir)
    if (
        ext_outcome is InstallOutcome.UNCHANGED
        and mcp_outcome is InstallOutcome.UNCHANGED
    ):
        return omp_dir, InstallOutcome.UNCHANGED
    return omp_dir, (InstallOutcome.CREATED if not existed else InstallOutcome.UPDATED)


def remove(project_dir: Path) -> tuple[Path, RemoveOutcome]:
    """Remove forseti's own extension file and `mcpServers.forseti` entry.

    No-ops -- and never creates either file -- if both are already absent or
    not forseti's own. Leaves every other file/key in `.omp/` untouched.
    """
    omp_dir = project_dir / ".omp"
    _, ext_outcome = _remove_extension(project_dir)
    _, mcp_outcome = _remove_mcp_config(project_dir)
    if (
        ext_outcome is RemoveOutcome.UNCHANGED
        and mcp_outcome is RemoveOutcome.UNCHANGED
    ):
        return omp_dir, RemoveOutcome.UNCHANGED
    return omp_dir, RemoveOutcome.REMOVED
