// >>> forseti (managed) -- do not edit; regenerated by
// `forseti enable-project --harness oh-my-pi` >>>
//
// Forseti's Oh My Pi extension (#249): after a `write`/`edit` tool call
// lands, shell out to `forseti omp-hook tool-result` and let it decide
// whether the edit's stored semantic properties still hold. All Core logic
// (ESBMC invocation, harness rendering, the property store) lives in the
// `forseti` CLI -- this extension only serializes the event, calls it, and
// applies its JSON reply to the tool result.
//
// Uses `node:child_process.spawnSync` rather than the extension API's own
// `pi.exec` helper: `pi.exec` streams stdout via an `onData` callback and
// has no stdin parameter, while `forseti omp-hook tool-result` expects one
// JSON object on stdin and prints one JSON reply on stdout -- the same
// contract `spawnSync`'s `input`/`stdout` options give directly.
//
// A `tool_result` handler's returned `isError` *is* applied by Oh My Pi's
// current `ExtensionToolWrapper` (verified against
// packages/coding-agent/src/extensibility/extensions/wrapper.ts), unlike
// the legacy `HookToolWrapper` docs/hooks.md describes -- so a VIOLATED
// verdict here reads to the model as the edit itself having failed, not
// merely as an aside.

import { spawnSync } from "node:child_process";
import type { HookAPI } from "@oh-my-pi/pi-coding-agent/extensibility/hooks";

const GATED_TOOLS = new Set(["write", "edit"]);

export default function forsetiGate(pi: HookAPI): void {
  pi.on("tool_result", async (event, ctx) => {
    if (!GATED_TOOLS.has(event.toolName) || event.isError) return;

    let reply: { decision?: string; reason?: string; systemMessage?: string };
    try {
      const proc = spawnSync("forseti", ["omp-hook", "tool-result"], {
        cwd: ctx.cwd,
        input: JSON.stringify({
          toolName: event.toolName,
          input: event.input,
          isError: event.isError,
          cwd: ctx.cwd,
        }),
        encoding: "utf-8",
        timeout: 180_000,
      });
      if (!proc.stdout?.trim()) return;
      reply = JSON.parse(proc.stdout);
    } catch {
      // A broken/missing `forseti` must not wedge the session over a
      // best-effort gate -- fail open, same as every other adapter's hook.
      return;
    }

    const message = reply.decision === "block" ? reply.reason : reply.systemMessage;
    if (!message) return;

    return {
      content: [...event.content, { type: "text" as const, text: message }],
      isError: reply.decision === "block" ? true : event.isError,
    };
  });
}
// <<< forseti (managed) <<<
