// >>> forseti (managed) -- do not edit; regenerated by
// `forseti enable-project --harness oh-my-pi` >>>
//
// Forseti's Oh My Pi extension (#249): after a `write`/`edit` tool call
// lands, shell out to `forseti omp-hook tool-result` and let it decide
// whether the edit's stored semantic properties still hold. All Core logic
// (ESBMC invocation, harness rendering, the property store) lives in the
// `forseti` CLI -- this extension only serializes the event, calls it, and
// applies its JSON reply to the tool result.
//
// Uses `node:child_process.spawnSync` rather than the extension API's own
// `pi.exec` helper: `pi.exec` streams stdout via an `onData` callback and
// has no stdin parameter, while `forseti omp-hook tool-result` expects one
// JSON object on stdin and prints one JSON reply on stdout -- the same
// contract `spawnSync`'s `input`/`stdout` options give directly.
//
// A `tool_result` handler's returned `isError` *is* applied by Oh My Pi's
// current `ExtensionToolWrapper` (verified against
// packages/coding-agent/src/extensibility/extensions/wrapper.ts), unlike
// the legacy `HookToolWrapper` docs/hooks.md describes -- so a VIOLATED
// verdict here reads to the model as the edit itself having failed, not
// merely as an aside.
//
// `spawnSync` does not throw on a launch failure or a timeout -- it returns
// normally with `error` set (Node.js semantics), so a killed/never-started
// `forseti` process must be checked explicitly rather than relied on to
// fall into a catch block. Every spawn failure (including `forseti` missing
// from PATH), a nonzero exit, or an unparseable reply is reported as an
// inconclusive result instead of read as a silent pass -- the empty-stdout
// case is a legitimate pass only when the process actually exited cleanly.

import { spawnSync } from "node:child_process";
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

const GATED_TOOLS = new Set(["write", "edit"]);

function notAPass(event: { content: unknown[] }, detail: string) {
  const text = `Forseti gate did not complete (${detail}). Not a pass.`;
  return { content: [...event.content, { type: "text" as const, text }] };
}

export default function forsetiGate(pi: ExtensionAPI): void {
  pi.on("tool_result", async (event, ctx) => {
    if (!GATED_TOOLS.has(event.toolName) || event.isError) return;

    const proc = spawnSync("forseti", ["omp-hook", "tool-result"], {
      cwd: ctx.cwd,
      input: JSON.stringify({
        toolName: event.toolName,
        input: event.input,
        isError: event.isError,
        cwd: ctx.cwd,
      }),
      encoding: "utf-8",
      timeout: 180_000,
    });

    if (proc.error) {
      return notAPass(event, proc.error.message);
    }
    if (proc.status !== 0) {
      return notAPass(event, `forseti exited ${proc.status}`);
    }

    const stdout = proc.stdout?.trim();
    if (!stdout) return; // main() printed nothing -- a legitimate pass

    let reply: { decision?: string; reason?: string; systemMessage?: string };
    try {
      reply = JSON.parse(stdout);
    } catch {
      return notAPass(event, "unparseable reply");
    }

    const message = reply.decision === "block" ? reply.reason : reply.systemMessage;
    if (!message) return;

    return {
      content: [...event.content, { type: "text" as const, text: message }],
      isError: reply.decision === "block" ? true : event.isError,
    };
  });
}
// <<< forseti (managed) <<<
